export const strings = {
  landing: {
    prompt: "C:\\LORDS_OF_LOGIC",
    title: "LORDS OF LOGIC",
    tagline: "dev trivia for software developers",
    description: [
      "// a quiz game for software developers.",
      "// fast, short rounds — 3 to 7 minutes.",
      "// web stack, platforms, and dev best practices.",
    ],
    play: "PLAY",
    ranking: "RANKING",
    login: "LOGIN",
    logout: "LOGOUT",
    hint: "// press TAB to enter the menu — ARROW KEYS to select, ENTER to run",
    version: "LORDS OF LOGIC v0.1.0",
  },
  login: {
    prompt: "C:\\LORDS_OF_LOGIC\\LOGIN>",
    title: "LOGIN",
    tagline: "authenticate to start playing",
    google: "SIGN IN WITH GOOGLE",
    discord: "SIGN IN WITH DISCORD",
    back: "< BACK",
    hint: "// pick a provider — google or discord only",
    errorGeneric: "ERROR: SIGN-IN FAILED",
    errorAuthCode: "ERROR: AUTH CODE EXCHANGE FAILED",
  },
  nickname: {
    prompt: "C:\\LORDS_OF_LOGIC\\NICKNAME>",
    title: "NICKNAME",
    tagline: "// the name shown on the global ranking",
    inputLabel: "NICKNAME:",
    keepDefault: "KEEP DEFAULT",
    confirm: "CONFIRM",
    back: "< BACK",
    hint: "// edit the name or keep the default",
    errorRequired: "ERROR: NICKNAME CANNOT BE EMPTY",
    errorTooLong: "ERROR: MAX 24 CHARACTERS",
    errorTaken: "ERROR: NICKNAME ALREADY TAKEN",
    errorFailed: "ERROR: COULD NOT SAVE NICKNAME",
  },
  play: {
    prompt: "C:\\LORDS_OF_LOGIC\\PLAY>",
    title: "PLAY",
    tagline: "pick a category",
    hint: "// 5 random questions · mixed difficulty · 15 seconds each",
    back: "< BACK",
  },
  ranking: {
    prompt: "C:\\LORDS_OF_LOGIC\\RANKING>",
    title: "RANKING",
    tagline: "top players by total xp",
    rank: "RANK",
    player: "PLAYER",
    titleCol: "TITLE",
    xp: "XP",
    matches: "MATCHES",
    previous: "< PREV",
    next: "NEXT >",
    page: (current: number, total: number) => `PAGE ${current}/${total}`,
    back: "< BACK",
    empty: "NO PLAYERS YET",
  },
  round: {
    prompt: (category: string) => `C:\\LORDS_OF_LOGIC\\PLAY\\${category}>`,
    questionLabel: (current: number, total: number) => `Q ${current}/${total}`,
    timeLeft: (seconds: number) => `TIME: ${seconds}S`,
    chooseHint: "// click an option to answer",
    typeHint: "// type your answer, then press ENTER",
    submit: "SUBMIT",
    next: "NEXT >",
    endRound: "END ROUND >",
    correct: "CORRECT:",
    wrong: "WRONG:",
    noAnswer: "NO ANSWER:",
    points: (points: number) => `${points > 0 ? "+" : ""}${points} PTS`,
    yourAnswer: "YOUR ANSWER:",
    correctAnswer: "CORRECT ANSWER:",
    scoreSoFar: "SCORE:",
    endTitle: "ROUND COMPLETE",
    totalScore: "TOTAL SCORE",
    xpEarned: "XP EARNED",
    playAgain: "PLAY AGAIN",
    backToLobby: "< BACK TO LOBBY",
    notRecorded: "// SIGN IN TO EARN XP — THIS ROUND WAS NOT RECORDED",
    hint: "// 5 questions · 15 seconds each",
    errorMatchNotFound: "ERROR: MATCH NOT FOUND",
    errorNoQuestions: "ERROR: NO QUESTIONS AVAILABLE",
  },
} as const;
